/usr/local/bin/python: can't open file '/root/PaddleNLP/llm/llama/auto_parallel/train_with_fleet.py': [Errno 2] No such file or directory
W0123 11:15:15.849715 45635 gpu_resources.cc:119] Please NOTE: device: 3, GPU Compute Capability: 8.0, Driver API Version: 12.0, Runtime API Version: 11.7
W0123 11:15:15.881254 45635 gpu_resources.cc:164] device: 3, cuDNN Version: 8.6.
I0123 11:15:17.824817 45635 tcp_utils.cc:107] Retry to connect to 10.78.110.139:38842 while the server is not yet listening.
I0123 11:15:20.825039 45635 tcp_utils.cc:130] Successfully connected to 10.78.110.139:38842
Tensor(shape=[10, 20], dtype=float32, place=Place(gpu:3), stop_gradient=True, process_mesh={shape: [2], process_ids: [2,3], dim_names: [y]}, placements=[Replicate()], GlobalDenseTensor=
       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1.]])
